### PR TITLE
Add detail

### PR DESCRIPTION
**Pull request by jeswr**
Adds detail to tokenized expressions; specifically

```ts
type details = {
    minChar : number; // Minimum number of characters required to 'satisfy' the regex component
    maxChar : number; // Maximum number of characters required to 'satisfy' the regex component
    regexString: string; // Regular expression (string version) that the token is representing
    regex : RegExp; // Regular expression (Regex Object with flags) that the token is representing
    fixed: boolean; // Whether this token has a 'fixed solution', e.g `(hello)`, or many solutions, e.g. `[0-9]`.
    stringOptions: string[] | undefined; // List of options that satisfy the token
    reference?: number;
    leftEnd: boolean; // Whether the '^' positional is applied or not; 
    rightEnd: boolean; // Whether the '$' positional is applied or not;
  } 
```

### CODE REVIEW

**Comment by fent** [comment]
> ```ts
> 
>     regexString: string; // Regular expression (string version) that the token is representing
> ```

isn't this already available through `regex.source`?

> ```ts
> 
>     reference?: number;
> ```

there's already the reference token right?

**Comment by jeswr** [comment]
> > ```ts
> >     regexString: string; // Regular expression (string version) that the token is representing
> > ```
> 
> isn't this already available through `regex.source`?
> 
> > ```ts
> >     reference?: number;
> > ```
> 
> there's already the reference token right?

Good point - once the reconstruction PR is accepted I'll merge those changes to this branch and make that fix.

The other thing that probably needs to be rethought is the `stringOptions` parameter, because so long as there are a finite number of values that satisfy a token - they will be generated here. This means that something like `addDetail(tokenize([a-z]{100}))` would just take over your RAM. Perhaps I just add an extra `maxOptions: number` parameter to addDetail wherein we stop providing options after the set of possible options exceeds that `maxOptions`?

**Comment by fent** [comment]
> The other thing that probably needs to be rethought is the `stringOptions` parameter, because so long as there are a finite number of values that satisfy a token - they will be generated here. This means that something like `addDetail(tokenize([a-z]{100}))` would just take over your RAM. Perhaps I just add an extra `maxOptions: number` parameter to addDetail wherein we stop providing options after the set of possible options exceeds that `maxOptions`?

hmm, i'm a bit hesitant of this field, it's starting to feel out of scope, and there's already [genex](https://www.npmjs.com/package/genex). a good rule of thumb can be having detail fields directly related to tokenized versions of a regex, but not the regex itself.

i forgot to ask, do you have a specific use case for this?

**Comment by jeswr** [comment]
> hmm, i'm a bit hesitant of this field, it's starting to feel out of scope, and there's already [genex](https://www.npmjs.com/package/genex). a good rule of thumb can be having detail fields directly related to tokenized versions of a regex, but not the regex itself.

That's reasonable - I also wasn't aware of genex and that appears to cover that functionality
> i forgot to ask, do you have a specific use case for this?

Yes - as part of a project (https://github.com/schimatos/schimatos.org/) that generates forms based on SHACL constraints (https://www.w3.org/TR/shacl/) we customize form fields based on the regular expression that an input must satisfy (for instance `/^\d{2}/\d{2}/\d{4}$/` would generate 3 separate fields to for users enter their date of birth in DD/MM/YY format). It *works* at the moment but there are many improvements that we want to make such as generating sample inputs, creating dropdowns if the set of possible inputs falls within a small set, being more accurate with the width of the input boxes based on the number of characters that can be entered into each field etc. Having a these kinds of details aids in doing this.

I'm also aiming to make that Regex field generator available as a standalone package at some point if time allows.

**Comment by charmander** [comment]
Couldn’t all of this be in a different package, since it isn’t related to parsing and doesn’t need internal information from the parser to work efficiently?

**Comment by jeswr** [comment]
> Couldn’t all of this be in a different package, since it isn’t related to parsing and doesn’t need internal information from the parser to work efficiently?

I see no reason why not esp. if you want to keep `ret.js` lightweight. I can package it up separately once `token-reconstruction` PR is merged if that is preferable.

**Comment by fent** [comment]
> I see no reason why not esp. if you want to keep `ret.js` lightweight. I can package it up separately once `token-reconstruction` PR is merged if that is preferable.

yep, i'm inclined to agree

**Pull request closed without merging**
