### PR TITLE
Typescript Typings

### LINKED ISSUE #16: Typings and SET Clarification
I'm currently updating my [`genex`](https://www.npmjs.com/package/genex) package to Typescript and while writing typings for `ret` I noticed this strange mention in the documentation that doesn't seem to make sense to me:

> **SET** Contains a key set specifying what tokens are allowed and a key not specifying if the set should be negated. A set can contain other sets, ranges, and characters.

In which cases would a `SET` token return other `SET` tokens? I can't think of an example for this.

---

Also, regarding typings, would you be willing to bundle them if I submit a PR? I currently have this:

```ts
declare function ret(input: string): ret.Root;

declare namespace ret {
  enum types {
    ROOT = 0,
    GROUP = 1,
    POSITION = 2,
    SET = 3,
    RANGE = 4,
    REPETITION = 5,
    REFERENCE = 6,
    CHAR = 7,
  }

  type Token = Group | Position | Set | Range | Repetition | Reference | Char;
  type Tokens = Root | Token;

  type Root = {
    type: types.ROOT;
    stack?: Token[];
    options?: Token[][];
  };

  type Group = {
    type: types.GROUP;
    remember: boolean;
    followedBy: boolean;
    notFollowedBy: boolean;
    stack?: Token[];
    options?: Token[][];
  };

  type Position = {
    type: types.POSITION;
    value: "^" | "$" | "B" | "b";
  };

  type Set = {
    type: types.SET;
    set: (Set | Range | Char)[];
    not: boolean;
  };

  type Range = {
    type: types.RANGE;
    from: number;
    to: number;
  };

  type Repetition = {
    type: types.REPETITION;
    min: number;
    max: number;
    value: Token;
  };

  type Reference = {
    type: types.REFERENCE;
    value: 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9;
  };

  type Char = {
    type: types.CHAR;
    value: number;
  };
}

export = ret;
```

### PR DESCRIPTION
**Pull request by alixaxel**
Closes #16

### CODE REVIEW

**Comment by fent** [comment]
Looks good, would prefer if the file was placed in a `typings` folder to keep things more organized.

In another topic slightly related to types but not to this PR, looking over the API, I feel like having both `options` and `stack` for `ROOT` and `GROUP` types is a bit confusing. Maybe we should only have one of them, and if the group doesn't have a pipe, then the field is still an array of array of tokens, but the array should contain only one list? What do you think?

**Comment by alixaxel** [comment]
@fent 

> Looks good, would prefer if the file was placed in a typings folder to keep things more organized.

Sure thing.

> if the group doesn't have a pipe, then the field is still an array of array of tokens

I think it's a good decision. That's exactly what I do to simplify follow up code:

https://github.com/alixaxel/genex.js/blob/40641a38bf8403fb66c3b1d5b37482c306d4e723/source/index.ts#L38-L41

Do you want the typings in to reflect this new 2-dimensional array stack?

**Comment by fent** [comment]
> Do you want the typings in to reflect this new 2-dimensional array stack?

Well what I was planning to do was something like your code. Keep `options` and remove `stack`. Or actually, keep `stack` around for a short while to support backwards compatibility.

But anyway, I can make the change to typings when I make the code changes.

**Comment by alixaxel** [comment]
@fent Just following up on this.

Do you want me to change this to the `typings` folder without the `options`/`stack` changes?

**Comment by fent** [comment]
Yep, I was waiting on that before reviewing

**Comment by alixaxel** [comment]
@fent Ah, some misunderstanding on my part, just pushed it. :smile:

**Comment by fent** [comment]
Thanks!

**Comment by alixaxel** [comment]
After deleting my local typings for `ret` and installing `0.3.0`, it's no longer able to find the typings:

image

**Comment by alixaxel** [comment]
@fent While moving the typings into `typings` directory, I forgot to specify it should also be bundled with the package. :confused:  Sorry about that! I submitted #19 to address this.

**Pull request merged**
